name: make

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: abel0b/setup-premake@v2.3
      with:
        version: "5.0.0-beta2"
    
    - name: Compile my project
      run: |
        premake5 gmake2
        make
